/*
 * This file was generated by orbit-idl-2 for Voyager - DO NOT EDIT!
 *
 *
 * And remember, phase 3 is near...
 */

#define INCL_DOS
#include <os2.h>

#include <string.h>
#include <glib.h>

#include "nomfilepath.ih"

NOM_Scope PNOMPath NOMLINK impl_NOMPath_appendPath(NOMPath* nomSelf, const PNOMPath nomPath, CORBA_Environment *ev)
{
/* NOMFilePathData* nomThis=NOMFilePathGetData(nomSelf); */
#warning !!!!! NOMPath_appendPath() is a stub !!!!!
  NOMPath_appendString((NOMString*) nomSelf, (NOMString*)nomPath, NULLHANDLE);
  return nomSelf;
}

