/*
 * This file was generated by orbit-idl-2 for Voyager - DO NOT EDIT!
 *
 *
 * And remember, phase 3 is near...
 */

#define INCL_DOS
#include <os2.h>

#include <string.h>
#include <glib.h>

#include "nomfilepath.ih"

NOM_Scope PNOMFilePath NOMLINK impl_NOMFilePath_appendPath(NOMFilePath* nomSelf, const PNOMFilePath nomFPath, CORBA_Environment *ev)
{
/* NOMFilePathData* nomThis=NOMFilePathGetData(nomSelf); */
#warning !!!!! NOMFilePath_appendPath() is a stub !!!!!
  NOMFilePath_appendString((NOMString*) nomSelf, (NOMString*)nomFPath, NULLHANDLE);
  return nomSelf;
}

