/*
 * This file was generated by orbit-idl-2 for Voyager - DO NOT EDIT!
 *
 *
 * And remember, phase 3 is near...
 */

#ifndef NOM_M_WPDrives_IMPLEMENTATION_FILE
#define NOM_M_WPDrives_IMPLEMENTATION_FILE
#endif

#define INCL_DOS
#include <os2.h>

#include "nom.h"
#include <nomtk.h>

#include "m_wpdrives.ih"


/* orbit-idl-c-stubs.c, cs_output_stub line 347 */
NOM_Scope CORBA_string NOMLINK impl_M_WPDrives_wpclsQueryTitle(M_WPDrives* nomSelf, CORBA_Environment *ev)
{
  M_WPDrivesData* nomThis=M_WPDrivesGetData(nomSelf);

#warning !!!!! This should not be an instance var !!!!!
  if(!_pChrTitle)
    {
      _pChrTitle="Drives Folder";
    }

  return _pChrTitle;

#if 0
  /* orbit-idl-c-stubs.c, VoyagerWriteProtoForParentCall line 119 */
  M_WPDrives_wpclsQueryTitle_parent(nomSelf,  ev);
#endif
}

