/* ***** BEGIN LICENSE BLOCK *****
* Version: CDDL 1.0/LGPL 2.1
*
* The contents of this file are subject to the COMMON DEVELOPMENT AND
* DISTRIBUTION LICENSE (CDDL) Version 1.0 (the "License"); you may not use
* this file except in compliance with the License. You may obtain a copy of
* the License at http://www.sun.com/cddl/
*
* Software distributed under the License is distributed on an "AS IS" basis,
* WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
* for the specific language governing rights and limitations under the
* License.
*
* The Original Code is "NOM" Netlabs Object Model
*
* The Initial Developer of the Original Code is
* netlabs.org: Chris Wohlgemuth <cinc-ml@netlabs.org>.
* Portions created by the Initial Developer are Copyright (C) 2005-2006
* the Initial Developer. All Rights Reserved.
*
* Contributor(s):
*
* Alternatively, the contents of this file may be used under the terms of
* the GNU Lesser General Public License Version 2.1 (the "LGPL"), in which
* case the provisions of the LGPL are applicable instead of those above. If
* you wish to allow use of your version of this file only under the terms of
* the LGPL, and not to allow others to use your version of this file under
* the terms of the CDDL, indicate your decision by deleting the provisions
* above and replace them with the notice and other provisions required by the
* LGPL. If you do not delete the provisions above, a recipient may use your
* version of this file under the terms of any one of the CDDL or the LGPL.
*
* ***** END LICENSE BLOCK ***** */
/*
 * This file was generated by orbit-idl-2 for Voyager
 *
 *
 * And remember, phase 3 is near...
 */

#define INCL_DOS
#include <os2.h>

#include "nom.h"
#include <nomtk.h>

#include <string.h>
#include "gtk/gtk.h"

#warning !!!!! nomIsObj() must be globaly defined !!!!!
#define nomIsObj(a) ((a)!= 0)

typedef struct _PRIVFOLDERDATA
{
  GtkListStore *gstoreFldContents;
  GtkWidget    *gtkIconView;
}PRIVFOLDERDATA, *PPRIVFOLDERDATA;

#include "wpfolder.ih"
#include "wpdatafile.h"

/* Enum for the folder store */
enum
{
  COL_PATH,
  COL_DISPLAY_NAME,
  COL_PIXBUF,
  COL_IS_DIRECTORY,
  NUM_COLS
};

static GtkListStore * fldr_CreateStore (void)
{
  GtkListStore *store;

  store = gtk_list_store_new (NUM_COLS,
			      G_TYPE_STRING, 
			      G_TYPE_STRING, 
			      GDK_TYPE_PIXBUF,
			      G_TYPE_BOOLEAN);

  return store;
}

static BOOL
fldr_fillStore (GtkListStore *store, const gchar* gchrPath)
{

  GDir *gDir;
  const gchar *gchrCurrentEntry;
  GtkTreeIter iter;
  
  /* First clear the store */
  gtk_list_store_clear (store);

  /* Now go through the directory and extract all the file
   * information */
  gDir = g_dir_open (gchrPath, 0, NULL);
  if (!gDir)
    return FALSE;

  while ((gchrCurrentEntry = g_dir_read_name (gDir))!= NULL)
    {
      gchar *path, *display_name;
      gboolean is_dir;

      if (gchrCurrentEntry[0] != '\0')
        {
          path = g_build_filename (gchrPath, gchrCurrentEntry, NULL);
          nomPrintf("  %s\n", path);          

          display_name = g_filename_to_utf8 (gchrCurrentEntry, -1, NULL, NULL, NULL);
          if(g_file_test (path, G_FILE_TEST_IS_DIR))
            {
              /* It's a folder */
              WPFolder* wpFolder;

              wpFolder=WPFolderNew();
              if(nomIsObj(wpFolder))
                {
                  gtk_list_store_append (store, &iter);
#if 0
                  gtk_list_store_set (store, &iter,
                                      COL_PATH, path,
                                      COL_DISPLAY_NAME, display_name,
                                      COL_IS_DIRECTORY, is_dir,
                                      COL_PIXBUF, _wpQueryIcon(wpFolder), //folder_pixbuf ,
                                      -1);
#endif
                }/* if(nomIsObj(wpFolder)) */
            }/* if(g_file_test (path, G_FILE_TEST_IS_DIR)) */
          else
            {
              /* It's a file */
              WPDataFile* wpDataFile;

              wpDataFile=WPDataFileNew();

              if(nomIsObj(wpDataFile))
                {
                  gtk_list_store_append (store, &iter);
#if 0
                  gtk_list_store_set (store, &iter,
                                      COL_PATH, path,
                                      COL_DISPLAY_NAME, display_name,
                                      COL_IS_DIRECTORY, is_dir,
                                      COL_PIXBUF, _wpQueryIcon(wpDataFile), //file_pixbuf,
                                      -1);
#endif
                }
            }
          g_free (path);
          g_free (display_name);
        }/* if (gchrCurrentEntry[0] != '\0') */
    }/* while */

  g_dir_close(gDir);

  return TRUE;
}

/* pszPath contains the fully qualified path (checked with WPS) */
NOM_Scope CORBA_boolean NOMLINK impl_WPFolder_wpPopulate(WPFolder* nomSelf, const CORBA_unsigned_long ulReserved, const CORBA_char * pszPath, const CORBA_boolean fFoldersOnly, CORBA_Environment *ev)
{
 WPFolderData* nomThis=WPFolderGetData(nomSelf); 
  GtkListStore* gStore;
  PPRIVFOLDERDATA priv;

  nomPrintf("    Entering %s with nomSelf: 0x%x. nomSelf is: %s. Path is %s\n",
            __FUNCTION__, nomSelf , nomSelf->mtab->nomClassName, pszPath);

  g_return_val_if_fail(_privFolderData!=NULLHANDLE, FALSE);      /* Huh! What happened in wpInitData()? */
  g_log("WPFolder", G_LOG_LEVEL_DEBUG, "%s: Populating %s\n", __FUNCTION__, pszPath);

#if 0
  /* Already populated? */
  if(fFoldersOnly && 
     (_wpQueryFldrFlags(somSelf) & (FOI_POPULATEDWITHFOLDERS | FOI_POPULATEDWITHALL)))
    return TRUE;
  else if(_wpQueryFldrFlags(somSelf) & FOI_POPULATEDWITHALL)
    return TRUE;
#endif

  priv=_privFolderData;

  if(!priv->gstoreFldContents)
    {
      /* Create a store holding the folder contents */
      gStore=fldr_CreateStore();
      g_return_val_if_fail(gStore!=NULLHANDLE, FALSE);
      priv->gstoreFldContents=gStore;
    }

  /* Fill our store */
  fldr_fillStore(gStore, pszPath);

#if 0
  gtk_icon_view_set_model(GTK_ICON_VIEW (priv->gtkIconView), GTK_TREE_MODEL (priv->gstoreFldContents));
  /* We now set which model columns that correspont to the text
   * and pixbuf of each item
   */
  gtk_icon_view_set_text_column (GTK_ICON_VIEW (priv->gtkIconView), COL_DISPLAY_NAME);
  gtk_icon_view_set_pixbuf_column (GTK_ICON_VIEW (priv->gtkIconView), COL_PIXBUF);
  gtk_icon_view_set_item_width (GTK_ICON_VIEW (priv->gtkIconView),
                                100);

  g_object_unref (gStore);
#endif
  return FALSE;
}


NOM_Scope void NOMLINK impl_WPFolder_wpInitData(WPFolder* nomSelf, CORBA_Environment *ev)
{
  gulong ulErr;
  WPFolderData* nomThis=WPFolderGetData(nomSelf); 

  /* orbit-idl-c-stubs.c, VoyagerWriteProtoForParentCall line 84 */
  WPFolder_wpInitData_parent(nomSelf,  ev);

  nomPrintf("    Entering %s with nomSelf: 0x%x. nomSelf is: %s.\n",
            __FUNCTION__, nomSelf , nomSelf->mtab->nomClassName);
  _privFolderData=_wpAllocMem((WPObject*)nomSelf, sizeof(PRIVFOLDERDATA), (CORBA_unsigned_long*)&ulErr, NULLHANDLE);
}

NOM_Scope void NOMLINK impl_WPFolder_wpOpen(WPFolder* nomSelf, CORBA_Environment *ev)
{
/* WPFolderData* nomThis=WPFolderGetData(nomSelf); */

#if 0
  /* orbit-idl-c-stubs.c, VoyagerWriteProtoForParentCall line 84 */
  WPFolder_wpOpen_parent(nomSelf,  ev);
#endif
}






