/*
 * This file was generated by orbit-idl-2 for Voyager - DO NOT EDIT!
 *
 *
 * And remember, phase 3 is near...
 */

#ifndef NOM_WPRootFolder_IMPLEMENTATION_FILE
#define NOM_WPRootFolder_IMPLEMENTATION_FILE
#endif

#define INCL_DOS
#include <os2.h>

#include "nom.h"
#include <nomtk.h>

#include "gtk/gtk.h"
/* Gui stuff */
#include "nomguitk.h"
#include "nomwindow.h"
#include "desktoptypes.h"
#include "wpnotebook.h"
#include "wpfolderwindow.h"
#include "wpfolder.h"
#include "m_wprootfolder.h"
#include "wprootfolder.ih"


/* orbit-idl-c-stubs.c, cs_output_stub line 347 */
NOM_Scope gpointer NOMLINK impl_WPRootFolder_wpOpen(WPRootFolder* nomSelf, const PWPFolderWindow nomFolder,
                                                    const gulong ulView, const nomId nameSpaceId, 
                                                    const gpointer pParam, CORBA_Environment *ev)
{
/* WPRootFolderData* nomThis=WPRootFolderGetData(nomSelf); */

#if 0
  /* orbit-idl-c-stubs.c, VoyagerWriteProtoForParentCall line 119 */
  WPRootFolder_wpOpen_parent(nomSelf,  ev);
#endif
}

