/*
 * This file was generated by orbit-idl-2 for Voyager - DO NOT EDIT!
 *
 *
 * And remember, phase 3 is near...
 */

/*
 * idl/wpnativetypes.idl
 */

#ifndef wpnativetypes_H
#define wpnativetypes_H 1

#include <glib.h>

#include <nomcls.h> /* This is needed for _nomNew() */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/** typedefs **/
/* from IDL source file "idl/wpnativetypes.idl" (seen 0, isTop 1, wasInhibit 0) */ 

/** stub prototypes **/
  /* (orbit-idl-c-headers.c, orbit_idl_output_c_headers line 65) */

/** Voyager **/
#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* wpnativetypes_H */
