/* ***** BEGIN LICENSE BLOCK *****
* Version: CDDL 1.0/LGPL 2.1
*
* The contents of this file are subject to the COMMON DEVELOPMENT AND
* DISTRIBUTION LICENSE (CDDL) Version 1.0 (the "License"); you may not use
* this file except in compliance with the License. You may obtain a copy of
* the License at http://www.sun.com/cddl/
*
* Software distributed under the License is distributed on an "AS IS" basis,
* WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
* for the specific language governing rights and limitations under the
* License.
*
* The Original Code is "NOM" Netlabs Object Model
*
* The Initial Developer of the Original Code is
* netlabs.org: Chris Wohlgemuth <cinc-ml@netlabs.org>.
* Portions created by the Initial Developer are Copyright (C) 2005-2006
* the Initial Developer. All Rights Reserved.
*
* Contributor(s):
*
* Alternatively, the contents of this file may be used under the terms of
* the GNU Lesser General Public License Version 2.1 (the "LGPL"), in which
* case the provisions of the LGPL are applicable instead of those above. If
* you wish to allow use of your version of this file only under the terms of
* the LGPL, and not to allow others to use your version of this file under
* the terms of the CDDL, indicate your decision by deleting the provisions
* above and replace them with the notice and other provisions required by the
* LGPL. If you do not delete the provisions above, a recipient may use your
* version of this file under the terms of any one of the CDDL or the LGPL.
*
* ***** END LICENSE BLOCK ***** */
/*
 * This file was generated by orbit-idl-2 for Voyager
 *
 *
 * And remember, phase 3 is near...
 */
#define INCL_DOS
#include <os2.h>

#include <nom.h>
#include <nomtk.h>

#include <string.h>
#include "wpobject.ih"

NOM_Scope gpointer NOMLINK impl_WPObject_wpAllocMem(WPObject* nomSelf, const CORBA_unsigned_long cbBytes,
                                                    CORBA_unsigned_long* prc, CORBA_Environment *ev)
{
/* WPObjectData* nomThis=WPObjectGetData(nomSelf); */
  gpointer nomRetval;

  return nomRetval;
}

NOM_Scope CORBA_boolean NOMLINK impl_WPObject_wpFreeMem(WPObject* nomSelf, const gpointer pByte, CORBA_Environment *ev)
{
/* WPObjectData* nomThis=WPObjectGetData(nomSelf); */
  CORBA_boolean nomRetval;

  return nomRetval;
}

NOM_Scope void NOMLINK impl_WPObject_nomInit(WPObject* nomSelf, CORBA_Environment *ev)
{
/* WPObjectData* nomThis=WPObjectGetData(nomSelf); */

  /* orbit-idl-c-stubs.c, VoyagerWriteProtoForParentCall line 84 */
  WPObject_nomInit_parent((NOMObject*) nomSelf,  ev);

  nomPrintf("    Entering %s with nomSelf: 0x%x. nomSelf is: %s.\n",
            __FUNCTION__, nomSelf , nomSelf->mtab->nomClassName);

  _wpInitData(nomSelf, ev);
}

NOM_Scope void NOMLINK impl_WPObject_nomUninit(WPObject* nomSelf, CORBA_Environment *ev)
{
/* WPObjectData* nomThis=WPObjectGetData(nomSelf); */

#if 0
  /* orbit-idl-c-stubs.c, VoyagerWriteProtoForParentCall line 84 */
  WPObject_nomUninit_parent(nomSelf,  ev);
#endif
}

NOM_Scope void NOMLINK impl_WPObject_wpInitData(WPObject* nomSelf, CORBA_Environment *ev)
{
/* WPObjectData* nomThis=WPObjectGetData(nomSelf); */

}

NOM_Scope void NOMLINK impl_WPObject_wpUnInitData(WPObject* nomSelf, CORBA_Environment *ev)
{
/* WPObjectData* nomThis=WPObjectGetData(nomSelf); */

}

NOM_Scope gpointer NOMLINK impl_WPObject_wpOpen(WPObject* nomSelf, const gpointer ptrReserved, const CORBA_unsigned_long ulView, const gpointer ptrParams, CORBA_Environment *ev)
{
/* WPObjectData* nomThis=WPObjectGetData(nomSelf); */
  gpointer nomRetval=NULLHANDLE;

  return nomRetval;
}
