/* ***** BEGIN LICENSE BLOCK *****
* Version: CDDL 1.0/LGPL 2.1
*
* The contents of this file are subject to the COMMON DEVELOPMENT AND
* DISTRIBUTION LICENSE (CDDL) Version 1.0 (the "License"); you may not use
* this file except in compliance with the License. You may obtain a copy of
* the License at http://www.sun.com/cddl/
*
* Software distributed under the License is distributed on an "AS IS" basis,
* WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
* for the specific language governing rights and limitations under the
* License.
*
* The Original Code is "NOM" Netlabs Object Model
*
* The Initial Developer of the Original Code is
* netlabs.org: Chris Wohlgemuth <cinc-ml@netlabs.org>.
* Portions created by the Initial Developer are Copyright (C) 2005-2006
* the Initial Developer. All Rights Reserved.
*
* Contributor(s):
*
* Alternatively, the contents of this file may be used under the terms of
* the GNU Lesser General Public License Version 2.1 (the "LGPL"), in which
* case the provisions of the LGPL are applicable instead of those above. If
* you wish to allow use of your version of this file only under the terms of
* the LGPL, and not to allow others to use your version of this file under
* the terms of the CDDL, indicate your decision by deleting the provisions
* above and replace them with the notice and other provisions required by the
* LGPL. If you do not delete the provisions above, a recipient may use your
* version of this file under the terms of any one of the CDDL or the LGPL.
*
* ***** END LICENSE BLOCK ***** */

#ifndef wpobject_idl
#define wpobject_idl

#include <nomobj.idl>

#include "wpnativetypes.idl"
#include "nomstring.idl"
#include "nommenu.idl"
#include "nommenuitem.idl"
#include "nomwindow.idl"

#ifndef NOMFolderWindow_defined
#define NOMFolderWindow_defined
native PNOMFolderWindow;
#endif

NOMCLASSNAME(WPObject);

#include "wpnotebook.idl"

interface WPObject : NOMObject
{
  NOMCLASSVERSION(1, 0);

  /* Memory allocation */
  gpointer wpAllocMem(in gulong cbBytes,
                      in pgulong prc);
  boolean  wpFreeMem(in gpointer pByte);
  void     wpInitData();
  void     wpUnInitData();
  gpointer wpOpen(in PNOMFolderWindow nomFolder, in gulong ulView, in gpointer pParam);
  void     wpLockObject();
  boolean  wpUnlockObject();
  boolean  wpObjectIsLocked();
  gpointer wpQueryIcon();
  unsigned long  wpRequestObjectMutexSem(in unsigned long ulReserved);
  unsigned long  wpReleaseObjectMutexSem();
  /*  boolean wpSetFolder(in WPFolder wpParentFolder); */

  PNOMString wpSetTitle(in PNOMString pnomStrNewTitle);
  PNOMString wpQueryTitle();

  PNOMMenu wpDisplayMenu(in PNOMFolderWindow nomFolder, in gpointer gReserved, in unsigned long ulMenuType,
                         in unsigned long ulReserved);
  void wpModifyMenu(in PNOMFolderWindow nomFolder, in PNOMMenu nomMenu, in unsigned long ulMenuType);
  void wpFilterMenu(in PNOMFolderWindow nomFolder, in PNOMMenu nomMenu, in unsigned long ulMenuType,
                    in unsigned long ulFlags);
  boolean wpMenuItemSelected(in PNOMFolderWindow nomFolder, in PNOMMenuItem nomMenuItem);
  void wpInsertMenuItem( in PNOMMenu nomMenu, in PNOMMenuItem nomMenuItem, in unsigned long ulPosition);

  /* Settings pages */
  boolean wpAddSettingsPages(in PWPNoteBook wpNoteBook);
  unsigned long wpInsertSettingsPage(in PWPNoteBook wpNoteBook, in gpointer ppageinfo);
  unsigned long wpAddObjectGeneralPage(in PWPNoteBook wpNoteBook);

  gpointer wpViewObject(in PNOMFolderWindow nomFolder, in gulong ulView, in gpointer pParam);
  gpointer wpSwitchTo(in gulong ulView);
  boolean wpRegisterView(in PNOMWindow pWindow, in PNOMString nomStrViewTitle);

  /* Inuse list methods */
  boolean   wpAddToObjUseList(in PUSEITEM pUseItem);
  boolean   wpDeleteFromObjUseList(in PUSEITEM pUseItem);
  PUSEITEM  wpFindUseItem( in gulong ulType, in PUSEITEM pCurrentUseItem);
  PVIEWITEM wpFindViewItem(in gulong flViews,in PVIEWITEM pCurrentItem);

  /* Methods overriden by this class */
  NOMOVERRIDE(nomInit);
  NOMOVERRIDE(nomUninit);

  /* Instancce variables of this class. Theses are not
     attributes. */
  NOMINSTANCEVAR(gint iLockCounter);
  NOMINSTANCEVAR(HMUX gObjectMutex);
  NOMINSTANCEVAR(PGSList glstObjectInUse);
  NOMINSTANCEVAR(PNOMString pnomStringTitle);

};

#endif





